# Site settings
title: Digital Rain Modern C++ Project Blog
author:
  name: Johnson Shogbaike
  email: your-email@domain.com
description: "A blog on a digital rain c++ project."

# Build settings
remote_theme: jekyll/minima
